config/routes.rb
Rails.application.routes.draw do

  resources :homework_submissions
  resources :lectures
  resources :course_sessions
  resources :homeworks do
    resources :homework_submissions
  end
  resources :mentors
  resources :application_questions

  get "/help/:page", to: "help#show"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'welcome#index'

  # okta saml authenticates by posting to the callback url
  get 'sessions/create'
  get 'sessions/destroy'
  get 'signout', to: 'sessions#destroy', as: 'signout'
  post "/auth/:provider/callback", to: "sessions#create"
  get "/login", to: 'sessions#new'
  get "/dev_login/:email", to: 'sessions#dev' if Rails.env.development?
  get "user/show", to: 'users#show'
  get "users/", to: 'users#index'

  put "users/make_admin/:id", to: 'users#make_admin', as: 'make_admin'
  put "users/revoke_admin/:id", to: 'users#revoke_admin', as: 'revoke_admin'

  #signing up to be a mentor

  #mentor routes
  get '/mentors', to: 'mentors#index'

  #
  # Students
  #
  get "students/apply"
  post "students/waitlist"
  get "students/waiting_list"
  post "students/application"
  put "students/approve_application/:id", to: 'admins#approve_student_application', as: 'approve_student_application'

  #
  # Admin special actions
  #
  get "admins/applications"
end

app/models/lecture.rb
class Lecture < ApplicationRecord
  belongs_to :course_session
  before_destroy :destroy_homeworks
  has_one :homework

  enum topic: [:ruby, :rails, :javascript, :react, :html, :sql, :other]

  @@topic_avatars = {
    ruby: "diamond",
    rails: "diamond",
    html: "html5",
    javascript: "js",
    react: "react",
    sql: "database",
    other: "code"
  }


  # better presentation of lecture datetime in user local time
  def scheduled_for_local
    self.schedule_date.localtime&.strftime("%Y/%m/%d at %I:%M%p")
  end

  def has_homework?
    !self.homework.nil?
  end

  def destroy_homeworks
    if has_homework?
      self.homework.destroy
    end
  end

  def lecture_avatar
    @@topic_avatars[self.topic.to_sym]
  end
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  before_action :set_lecture, only: [:show, :edit, :update, :destroy]
  before_action :set_course_session, only: [:new]

  # GET /lectures
  # GET /lectures.json
  def index
    @lectures = Lecture.all
  end

  # GET /lectures/1
  # GET /lectures/1.json
  def show
  end

  # GET /lectures/new
  def new
    @lecture = @course_session.lectures.new
  end

  # GET /lectures/1/edit
  def edit
  end

  # POST /lectures
  # POST /lectures.json
  def create
    @course_session = CourseSession.find(params[:lecture][:course_session_id])
    @lecture = @course_session.lectures.build(lecture_params)

    respond_to do |format|
      if @lecture.save
        format.html { redirect_to @lecture.course_session, notice: 'Lecture was successfully created.' }
        format.json { render :show, status: :created, location: @lecture }
      else
        format.html { render :new }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lectures/1
  # PATCH/PUT /lectures/1.json
  def update
    respond_to do |format|
      if @lecture.update(lecture_params)
        format.html { redirect_to @lecture.course_session, notice: 'Lecture was successfully updated.' }
        format.json { render :show, status: :ok, location: @lecture }
      else
        format.html { render :edit }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lectures/1
  # DELETE /lectures/1.json
  def destroy
    course_session_id = @lecture.course_session_id
    @lecture.destroy
    respond_to do |format|
      format.html { redirect_to course_session_path(course_session_id), notice: 'Lecture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_lecture
    @lecture = Lecture.find(params[:id])
  end

  def set_course_session
    @course_session = CourseSession.find(params[:format])
  end

  # Only allow a list of trusted parameters through.
  def lecture_params
    lp = params.require(:lecture).permit(:lecture_name, :lecture_content, :video_link, :teacher_id, :schedule_date, :topic)
    lp[:topic] = params[:lecture][:topic].to_i
    return lp
  end
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/views/lectures/_form.html.erb
<%= form_with(model: lecture, local: true) do |form| %>
  <div class="card p-5" style="width: 48rem;">
    <%= form.hidden_field :course_session_id, value: params[:format] %>

    <div class="form-group">
      <%= form.label :lecture_name, class: "input-group mb-3" %>
      <%= form.text_field :lecture_name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :lecture_content, class: "input-group mb-3" %>
      <%= form.text_field :lecture_content, class: "form-control" %>
    </div>

    <div class="form_group">
      <%= form.label :topic, class: "input-group mb-3" %>
      <%= form.select :topic, options_for_select(Lecture.topics, selected: Lecture.topics[lecture.topic]), {}, class: "form-control mb-3 form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :schedule_date, class: "input-group mb-3" %>
      <%= form.datetime_field :schedule_date, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :video_link, class: "input-group mb-3" %>
      <%= form.text_field :video_link, class: "form-control" %>
    </div>


    <div class="form-group">
      <%= form.label :teacher_id, class: "input-group mb-3" %>
      <%= form.number_field :teacher_id, class: "form-control" %>
    </div>

    <div class="actions">
      <%= form.submit class: "btn btn-primary"%>
    </div>
  <% end %>
  </div>

app/views/lectures/edit.html.erb
<div class="container mb-auto py-3 text-center">
  <h2>Editing Lecture</h2>
</div>

<div class="container d-flex justify-content-center">
  <%= render 'form', lecture: @lecture %>
</div>


<%= link_to 'Show', @lecture %> |
<%= link_to 'Back', course_session_path(@lecture.course_session_id) %>

app/views/lectures/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container mb-auto py-3 text-center">
  <h2>Lectures</h2>
</div>

<table>
  <thead>
    <tr>
      <th>Lecture ID</th>
      <th>Lecture name</th>
      <th>Lecture content</th>
      <th>Video recording link</th>
      <th>Homework</th>
      <th>Teacher</th>
      <th>Carrot U Session</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lectures.each do |lecture| %>
      <tr>
        <td><%= lecture.id %></td>
        <td><%= lecture.lecture_name %></td>
        <td><%= lecture.lecture_content %></td>
        <td><%= lecture.video_link %></td>
        <td><%= lecture.homework_id %></td>
        <td><%= lecture.teacher_id %></td>
        <td><%= lecture.course_session_id %></td>
        <td><%= link_to 'Show', lecture %></td>
        <td><%= link_to 'Edit', edit_lecture_path(lecture) %></td>
        <td><%= link_to 'Destroy', lecture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lecture', new_lecture_path %>

app/views/lectures/new.html.erb
<div class="container mb-auto py-3 text-center">
  <h2>Create Lecture</h2>
</div>

<div class="container d-flex justify-content-center">
  <%= render 'form', url: lectures_path, lecture: @lecture %>
</div>

<%= link_to 'Back', course_session_path(@lecture.course_session_id) %>

app/views/lectures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lecture ID:</strong>
  <%= @lecture.id %>
</p>

<p>
  <strong>Lecture name:</strong>
  <%= @lecture.lecture_name %>
</p>

<p>
  <strong>Lecture content:</strong>
  <%= @lecture.lecture_content %>
</p>

<p>
  <strong>Video recording link:</strong>
  <%= @lecture.video_link %>
</p>

<p>
  <strong>Carrot U Session:</strong>
  <%= @lecture.course_session_id %>
</p>

<p>
  <strong>Teacher:</strong>
  <%= @lecture.teacher_id %>
</p>

<p>
  <strong>Homework:</strong>
  <% if @lecture.has_homework? %>
    <%= @lecture.homework.content %>
  <% else %>
    <%= link_to 'Add Homework', new_homework_path(@lecture.id) %>
  <% end %>
</p>

<%= link_to 'Edit', edit_lecture_path(@lecture) %> |
<%= link_to 'Back', course_session_path(@lecture.course_session_id) %>