config/routes.rb
Rails.application.routes.draw do

  resources :homework_submissions
  resources :lectures
  resources :course_sessions
  resources :homeworks do
    resources :homework_submissions
  end
  resources :mentors
  resources :application_questions

  get "/help/:page", to: "help#show"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'welcome#index'

  # okta saml authenticates by posting to the callback url
  get 'sessions/create'
  get 'sessions/destroy'
  get 'signout', to: 'sessions#destroy', as: 'signout'
  post "/auth/:provider/callback", to: "sessions#create"
  get "/login", to: 'sessions#new'
  get "/dev_login/:email", to: 'sessions#dev' if Rails.env.development?
  get "user/show", to: 'users#show'
  get "users/", to: 'users#index'

  put "users/make_admin/:id", to: 'users#make_admin', as: 'make_admin'
  put "users/revoke_admin/:id", to: 'users#revoke_admin', as: 'revoke_admin'

  #signing up to be a mentor

  #mentor routes
  get '/mentors', to: 'mentors#index'

  #
  # Students
  #
  get "students/apply"
  post "students/waitlist"
  get "students/waiting_list"
  post "students/application"
  put "students/approve_application/:id", to: 'admins#approve_student_application', as: 'approve_student_application'

  #
  # Admin special actions
  #
  get "admins/applications"
end

app/models/application_answer.rb
class ApplicationAnswer < ApplicationRecord
  belongs_to :course_session_participant

  STUDENT_APPLICATION_QUESTIONS = {
    department: "Department",
    start_date: "Start date",
    code_sample: "Code sample",
    project: "Project description",
    why_carrot_u: "Why join Carrot U?",
    goal: "Study goal"
  }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course_session.rb
class CourseSession < ApplicationRecord
  has_many :lectures
  has_many :course_session_participants
  before_destroy :destroy_lectures
  validates :name, presence: true

  scope :students, -> { joins(:course_session_participants).merge(CourseSessionParticipant.student) }

  enum status: [:draft, :admissions, :active, :finished, :archived]

  @@badges = {
    draft: "light",
    admissions: "primary",
    active: "success",
    finished: "warning",
    archived: "secondary"
  }

  class << self
    def accepting_applications
      CourseSession.where("status = ?", statuses["admissions"]).
        order("start_date ASC")
    end
  end

  #
  # Instance methods
  #

  # careful with using this, make sure the call site fits the context
  def start_to_s
    if !self.start_date?
      "Session start date has not been scheduled."
    elsif self.start_date > Time.now
      "Starts " +  self.start_date&.strftime('%m-%d-%Y') if self.start_date?
    else
      "Started " +  self.start_date&.strftime('%m-%d-%Y') if self.start_date?
    end
  end

  def destroy_lectures
    self.lectures.destroy_all
  end

  def status_badge
    "badge badge-pill badge-#{@@badges[self.status.to_sym]}"
  end
end

app/models/homework.rb
class Homework < ApplicationRecord
  belongs_to :lecture
  has_many :homework_submissions

  def get_course_session_id
    @lecture = Lecture.find(self.lecture_id)
    @lecture.course_session_id
  end

  def get_lecture_name
    @lecture = Lecture.find(self.lecture_id)
    @lecture.lecture_name
  end

  def due_date_to_s
    return self.due_date&.strftime("%m-%d-%y")
  end
end

app/models/homework_submission.rb
class HomeworkSubmission < ApplicationRecord
  belongs_to :course_session_participant
  belongs_to :homework
end

app/models/lecture.rb
class Lecture < ApplicationRecord
  belongs_to :course_session
  before_destroy :destroy_homeworks
  has_one :homework

  enum topic: [:ruby, :rails, :javascript, :react, :html, :sql, :other]

  @@topic_avatars = {
    ruby: "diamond",
    rails: "diamond",
    html: "html5",
    javascript: "js",
    react: "react",
    sql: "database",
    other: "code"
  }


  # better presentation of lecture datetime in user local time
  def scheduled_for_local
    self.schedule_date.localtime&.strftime("%Y/%m/%d at %I:%M%p")
  end

  def has_homework?
    !self.homework.nil?
  end

  def destroy_homeworks
    if has_homework?
      self.homework.destroy
    end
  end

  def lecture_avatar
    @@topic_avatars[self.topic.to_sym]
  end
end

app/models/mentor.rb
class Mentor < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true
require "digest"

class User < ApplicationRecord
  has_many :users_managers

  before_save :compute_name_from_email

  # compute the name from the email if it is not already present
  def compute_name_from_email
    if self.name.blank?
      self.name = self.email.split('@').first.split('.').map(&:capitalize).join(' ')
    end
  end

  # creates MD5 hash of lowercase email and formats image url for gravatar avatar
  def gravatar_url
    @md5 = Digest::MD5.hexdigest self.email.downcase
    "https://www.gravatar.com/avatar/" + @md5 + "?d=mp"
  end

  def created_date_local
    self.created_at.localtime.strftime('%m-%d-%y')
  end

  def manager
    self.users_managers.current.first&.manager
  end

  # meh, it's not great but its the best we can do until we separate the name attribute
  def first_name
    name&.split&.first
  end

  def last_name
    name&.split&.last
  end
end

app/models/users_manager.rb
class UsersManager < ApplicationRecord
  belongs_to :user
  belongs_to :manager, class_name: "User"

  scope :current, -> { where(current: true).first }
end

app/models/waiting_list.rb
class WaitingList < ApplicationRecord
  belongs_to :user
  belongs_to :course_session, optional: true

  scope :current, -> { where(course_session: nil).includes(:user) }

  class << self
    def notify_course_session_open(course_session)
      current.each do |waiting_list|
        CourseSessionMailer.with(course_session: course_session, user: waiting_list.user).session_open_email.deliver_later
        waiting_list.update(course_session: course_session)
      end
    end
  end
end

app/controllers/help_controller.rb
class HelpController < ApplicationController
  def show
    render template: "help/#{params[:page]}"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
  def student_application_question(question_key)
    ApplicationAnswer::STUDENT_APPLICATION_QUESTIONS[question_key.to_sym] || question_key.capitalize.split('_').join(' ')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/helpers/mentors_helper.rb
module MentorsHelper
end

app/helpers/sign_up_helper.rb
module SignUpHelper
end

app/helpers/students_helper.rb
module StudentsHelper
  def answer_value(question_key, default_value=nil)
    @answers.find { |answer| answer.question_key == question_key }&.answer || default_value
  end

  def default_code_sample
    StudentsController::DEFAULT_CODE_SAMPLE
  end

  def goal_options
    goals = [
      "-- Select a goal --",
      "Move into a full time engineering role at Instacart",
      "Use new skills in your current role",
      "Use new skills to pursue another job outside of Instacart",
      "Other"
    ]
    options_for_select(goals, disabled: goals.first)
  end
end

app/views/admins/applications.html.erb
<% @applications.each do |application| %>
  <div class="card border-primary m-5">
    <h5 class="card-header">Applicant: <%= application.user.name %></h5>
    <div class="card-body">
      <div class="row">
        <div class="col-sm-6">
          <p class="card-text">
            Manager: <%= application.user.manager.email %>
            <br/>
            Approval: <%= application.manager_approved_at || "Pending" %>
          </p>
        </div>
        <div class="col-sm-6 text-right">
          <p class="card-text">
            Application date: <%= application.created_at %>
          </p>
        </div>
      </div>
      <% application.application_answers.each do |answer| %>
        <div class="card border-light">
          <h6 class="card-header">
            <%= student_application_question(answer.question_key) %>
          </h6>
          <div class="card-body">
            <pre><%= answer.answer %></pre>
          </div>
        </div>
      <% end %>
      </div>
      <div class="card-footer">
        <div class="row">
          <div class="col-sm-6">
            <%= link_to "Approve application", approve_student_application_path(application), class: "btn btn-success",  :remote=>true,:method=>"PUT" %>
          </div>
          <div class="col-sm-6">
            <a href="#" class="btn btn-danger">Deny application</a>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/admins/index.html.erb
<div>
  <% if logged_in? %>
    <nav class="navbar bg-light">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a>
            <%= link_to "Manage Users", users_path, class: "nav-link", id: "users" %> 
          </a>
        </li>
        <li class="nav-item">
          <%= link_to "Manage Questions for Application Form Template ", application_questions_path, class: "nav-link", id: "questions" %>
        </li>
      </ul>
    </nav>
  <% else %>
    <p>Please log in</p>
  <% end %>
</div>