config/routes.rb
Rails.application.routes.draw do

  resources :homework_submissions
  resources :lectures
  resources :course_sessions
  resources :homeworks do
    resources :homework_submissions
  end
  resources :mentors
  resources :application_questions

  get "/help/:page", to: "help#show"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'welcome#index'

  # okta saml authenticates by posting to the callback url
  get 'sessions/create'
  get 'sessions/destroy'
  get 'signout', to: 'sessions#destroy', as: 'signout'
  post "/auth/:provider/callback", to: "sessions#create"
  get "/login", to: 'sessions#new'
  get "/dev_login/:email", to: 'sessions#dev' if Rails.env.development?
  get "user/show", to: 'users#show'
  get "users/", to: 'users#index'

  put "users/make_admin/:id", to: 'users#make_admin', as: 'make_admin'
  put "users/revoke_admin/:id", to: 'users#revoke_admin', as: 'revoke_admin'

  #signing up to be a mentor

  #mentor routes
  get '/mentors', to: 'mentors#index'

  #
  # Students
  #
  get "students/apply"
  post "students/waitlist"
  get "students/waiting_list"
  post "students/application"
  put "students/approve_application/:id", to: 'admins#approve_student_application', as: 'approve_student_application'

  #
  # Admin special actions
  #
  get "admins/applications"
end

app/models/course_session.rb
class CourseSession < ApplicationRecord
  has_many :lectures
  has_many :course_session_participants
  before_destroy :destroy_lectures
  validates :name, presence: true

  scope :students, -> { joins(:course_session_participants).merge(CourseSessionParticipant.student) }

  enum status: [:draft, :admissions, :active, :finished, :archived]

  @@badges = {
    draft: "light",
    admissions: "primary",
    active: "success",
    finished: "warning",
    archived: "secondary"
  }

  class << self
    def accepting_applications
      CourseSession.where("status = ?", statuses["admissions"]).
        order("start_date ASC")
    end
  end

  #
  # Instance methods
  #

  # careful with using this, make sure the call site fits the context
  def start_to_s
    if !self.start_date?
      "Session start date has not been scheduled."
    elsif self.start_date > Time.now
      "Starts " +  self.start_date&.strftime('%m-%d-%Y') if self.start_date?
    else
      "Started " +  self.start_date&.strftime('%m-%d-%Y') if self.start_date?
    end
  end

  def destroy_lectures
    self.lectures.destroy_all
  end

  def status_badge
    "badge badge-pill badge-#{@@badges[self.status.to_sym]}"
  end
end

app/controllers/course_sessions_controller.rb
class CourseSessionsController < ApplicationController
  before_action :set_course_session, only: [:show, :edit, :update, :destroy]

  # GET /course_sessions
  def index
    @course_sessions = CourseSession.all
  end

  # GET /course_sessions/1
  def show
  end

  # GET /course_sessions/new
  def new
    @course_session = CourseSession.new
  end

  # GET /course_sessions/1/edit
  def edit
  end

  # POST /course_sessions
  def create
    @course_session = CourseSession.new(course_session_params)

    respond_to do |format|
      if @course_session.save
        format.html { redirect_to @course_session, notice: 'Course_session was successfully created.' }
        format.json { render :show, status: :created, location: @course_session }
      else
        format.html { render :new }
        format.json { render json: @course_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /course_sessions/1
  # PATCH/PUT /course_sessions/1.json
  def update
    respond_to do |format|
      if @course_session.update(course_session_params)
        # send an email here if the session is open for applications
        if @course_session.admissions?
          WaitingList.notify_course_session_open(@course_session)
        end
        format.html { redirect_to @course_session, notice: 'Course session was successfully updated.' }
        format.json { render :show, status: :ok, location: @course_session }
      else
        format.html { render :edit }
        format.json { render json: @course_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /course_session/1
  # DELETE /course_session/1.json
  def destroy
    @course_session.destroy_lectures
    @course_session.destroy
    respond_to do |format|
      format.html { redirect_to course_sessions_url, notice: 'Course_session was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_course_session
        @course_session = CourseSession.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def course_session_params
         csp = params.require(:course_session).permit(:name, :description, :start_date, :end_date, :repository_link, :status)
         csp[:status] = params[:course_session][:status].to_i
         return csp
      end

      def destroy_lectures
        self.lectures.destroy_all
      end
  end

app/views/course_sessions/_form.html.erb
<%= form_with(model: course_session, local: true) do |form| %>
  <% if course_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course_session.errors.count, "error") %> prohibited this lecture from being saved:</h2>

      <ul>
        <% course_session.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="card p-5" style="width: 48rem;">
    <div class="form-group">
      <%= form.label :name, class: "input-group mb-3" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :description, class: "input-group mb-3" %>
      <%= form.text_field :description, class: "form-control" %>
    </div>

    <div class="form_group">
      <%= form.label :status, class: "input-group mb-3" %>
      <%= form.select :status, options_for_select(CourseSession.statuses, selected: CourseSession.statuses[course_session.status]), {} ,class: "form-control mb-3 form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :start_date, class: "input-group mb-3" %>
      <%= form.date_field :start_date, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :end_date, class: "input-group mb-3" %>
      <%= form.date_field :end_date, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :repository_link, class: "input-group mb-3" %>
      <%= form.text_field :repository_link, class: "form-control" %>
    </div>

    <div class="actions">
      <%= form.submit class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/course_sessions/edit.html.erb
<div class="container mb-auto py-3 text-center">
  <h2>Editing Carrot U Session</h2>
</div>

<div class="container d-flex justify-content-center">
  <%= render 'form', course_session: @course_session %>
</div>
<%= link_to 'Show', @course_session %> |
<%= link_to 'Back', course_session_path(@course_session) %>

app/views/course_sessions/index.html.erb
<div class="container mb-auto py-3 text-center">
  <h2>Carrot U Sessions</h2>
</div>

<div class="container mx-auto">
  <p id="notice"><%= notice %></p>
  <% @course_sessions.each do |course_session| %>
    <div class="card bg-white mb-3" style="max-width: 100rem;">
      <div class="card-header">
        <%= course_session.name %>
        <%= link_to fa_icon("trash"), course_session, class: "float-right px-3", method: :delete, data: { confirm: 'Are you sure?' } if @current_user.admin %>
        <%= link_to fa_icon("edit"), edit_course_session_path(course_session), class: "float-right" if @current_user.admin %>
        <%= content_tag(:span, course_session.status, class: course_session.status_badge) %>
      </div>
      <div class="card-title p-3">
        <h5><%= course_session.start_to_s %></h5>
      </div>
      <div class = "card-body px-3 py-1">
        <%= link_to fa_icon("github") + " View Github Repository", course_session.repository_link, class: "float-left" if course_session.repository_link? %>
        <%= link_to "View Session Details", course_session_path(course_session), class: "float-right" %>
      </div>
    </div>
  <% end %>

  <% if @current_user.admin %>
    <div class = "card px-3 py-3 mb-3">
      <%= link_to '+ Add Course Session', new_course_session_path %>
    </div>
  <% end %>
</div>

app/views/course_sessions/new.html.erb
<div class="container mb-auto py-3 text-center">
  <h2>Create Carrot U Session</h2>
</div>

<div class="container d-flex justify-content-center">
  <%= render 'form', course_session: @course_session %>
</div>

<%= link_to 'Back', course_sessions_path %>

app/views/course_sessions/show.html.erb
<div id="notice"><%= notice %></div>

<div class="container mb-auto py-3 text-center">
    <h1><%= @course_session.name %></h1>
    <p><%= @course_session.description %></p>
    <%= link_to fa_icon("github"), @course_session.repository_link %> |
    <% if @current_user.admin %>
      <%= link_to 'edit session', edit_course_session_path(@course_session) %> |

    <% end %>
    <%= link_to 'sessions list', course_sessions_path %>
</div>

<div class="container mx-auto">
  <% @course_session.lectures.order('schedule_date ASC').each do |lecture| %>
    <div class="card mb-3" style="max-width: 100rem;">
      <div class="row no-gutters">
        <div class="col-md-2 bg-secondary text-center d-flex flex-column justify-content-center text-light">
          <%= fa_icon (lecture.lecture_avatar + " 4x"), class: "mx-auto my-2 text-light" if lecture.topic? %>
          <h5><%= lecture&.topic %></h5>
        </div>
        <div class="col-md-10">
          <div class="card-body">
            <h5>
              <%= lecture.lecture_name %>
              <% if @current_user.admin %>
                <%= link_to fa_icon("trash"), lecture, class: "float-right px-3", method: :delete, data: { confirm: 'Are you sure?' } %>
                <%= link_to fa_icon("edit"), edit_lecture_path(lecture), class: "float-right" %>
              <% end %>
            </h5>
            <p class="card-text"><%= lecture.lecture_content %></p>
            <p class="text-left"></p>
            <% if lecture.has_homework? %>
              <%= link_to "Homework: " + lecture.homework.content.to_s, homework_path(lecture.homework), class: "float-right" %>
            <% else %>
              <%= link_to 'Add Homework', new_homework_path(lecture.id), class: "float-right" if @current_user.admin %>
            <% end %>
            <p class="card-text">
              <small class="text-muted"><%= "Lecture Date: " + lecture.scheduled_for_local if lecture.schedule_date? %></small>
              <%= link_to "View Lecture", lecture&.video_link, class: "pr-2" if lecture.video_link? %>
            </p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <% if @current_user.admin %>
    <div class = "card px-3 py-3 mb-3">
      <%= link_to '+ Add Lecture', new_lecture_path(@course_session.id) %>
    </div>
  <% end %>
</div>