config/routes.rb
Rails.application.routes.draw do

  resources :homework_submissions
  resources :lectures
  resources :course_sessions
  resources :homeworks do
    resources :homework_submissions
  end
  resources :mentors
  resources :application_questions

  get "/help/:page", to: "help#show"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'welcome#index'

  # okta saml authenticates by posting to the callback url
  get 'sessions/create'
  get 'sessions/destroy'
  get 'signout', to: 'sessions#destroy', as: 'signout'
  post "/auth/:provider/callback", to: "sessions#create"
  get "/login", to: 'sessions#new'
  get "/dev_login/:email", to: 'sessions#dev' if Rails.env.development?
  get "user/show", to: 'users#show'
  get "users/", to: 'users#index'

  put "users/make_admin/:id", to: 'users#make_admin', as: 'make_admin'
  put "users/revoke_admin/:id", to: 'users#revoke_admin', as: 'revoke_admin'

  #signing up to be a mentor

  #mentor routes
  get '/mentors', to: 'mentors#index'

  #
  # Students
  #
  get "students/apply"
  post "students/waitlist"
  get "students/waiting_list"
  post "students/application"
  put "students/approve_application/:id", to: 'admins#approve_student_application', as: 'approve_student_application'

  #
  # Admin special actions
  #
  get "admins/applications"
end

app/models/homework_submission.rb
class HomeworkSubmission < ApplicationRecord
  belongs_to :course_session_participant
  belongs_to :homework
end

app/controllers/homework_submissions_controller.rb
class HomeworkSubmissionsController < ApplicationController
  before_action :set_homework_submission, only: [:new, :create, :show, :edit, :update, :destroy]

  # GET /homework_submissions
  # GET /homework_submissions.json
  def index
    @homework_submissions = HomeworkSubmission.all
  end

  # GET /homework_submissions/1
  # GET /homework_submissions/1.json
  def show
  end

  # GET /homework_submissions/new
  def new
  end

  # GET /homework_submissions/1/edit
  def edit
  end

  # POST /homework_submissions
  # POST /homework_submissions.json
  def create
    @homework_submission.pull_request = homework_submission_params[:pull_request]
    @homework_submission.is_public = true
    @homework_submission.user_id = current_user.id

    respond_to do |format|
      if @homework_submission.save
        format.html {redirect_to @homework_submission, notice: 'Homework submission was successfully created.'}
        format.json {render :show, status: :created, location: @homework_submission}
      else
        format.html {render :new}
        format.json {render json: @homework_submission.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /homework_submissions/1
  # PATCH/PUT /homework_submissions/1.json
  def update
    respond_to do |format|
      if @homework_submission.update(homework_submission_params)
        format.html {redirect_to @homework_submission, notice: 'Homework submission was successfully updated.'}
        format.json {render :show, status: :ok, location: @homework_submission}
      else
        format.html {render :edit}
        format.json {render json: @homework_submission.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /homework_submissions/1
  # DELETE /homework_submissions/1.json
  def destroy
    @homework_submission.destroy
    respond_to do |format|
      format.html {redirect_to homework_submissions_url, notice: 'Homework submission was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_homework_submission
    if params[:id]
      @homework_submission = HomeworkSubmission.find(params[:id])
    else
      homework_id = params[:homework_id] || homework_submission_params[:homework_id]
      @homework_submission = HomeworkSubmission.find_or_initialize_by(homework_id: homework_id, course_session_participant: student)
    end
  end

  # Only allow a list of trusted parameters through.
  def homework_submission_params
    params.require(:homework_submission).permit(:homework_id, :pull_request, :is_public, :user_id)
  end
end

app/views/homework_submissions/_form.html.erb
<%= form_with(model: homework_submission, local: true) do |form| %>
  <% if homework_submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(homework_submission.errors.count, "error") %> prohibited this homework_submission from being saved:</h2>

      <ul>
        <% homework_submission.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.hidden_field :homework_id, value: @homework_submission.homework_id %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="card p-5" style="width: 48rem;">
    <div class="form-group">
      <h5>Lecture: <%= homework_submission.homework.get_lecture_name %></h5>
    </div>

    <div class="form-group">
      <h6>Description</h6>
      <%= homework_submission.homework.description %>
    </div>

    <div class="form-group">
      <h6><%= form.label :pull_request, class: "input-group mb-3" %></h6>
      <%= form.text_field :pull_request, class: "form-control" %>
    </div>

    <div class="actions">
      <%= form.submit class: "btn btn-primary"%>
    </div>
  </div>
<% end %>

app/views/homework_submissions/edit.html.erb
<div class="container mb-auto py-3 text-center">
    <h2>Editing Homework Submission</h2>
</div>

<div class="container d-flex justify-content-center">
    <%= render 'form', homework_submission: @homework_submission %>
</div>

<%= link_to 'Show', @homework_submission %> |
<%= link_to 'Course Session', course_session_path(@homework_submission.course_session_participant.course_session_id) %> |
<%= link_to 'Homeworks', homeworks_path %>

app/views/homework_submissions/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container mb-auto py-3 text-center">
  <h2>Homework Submissions</h2>
</div>

<table>
  <thead>
    <tr>
      <th>Course session user</th>
      <th>Homework</th>
      <th>Pull request</th>
      <th>Is public</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @homework_submissions.each do |homework_submission| %>
      <tr>
        <td><%= homework_submission.course_session_participant_id %></td>
        <td><%= homework_submission.homework_id %></td>
        <td><%= homework_submission.pull_request %></td>
        <td><%= homework_submission.is_public %></td>
        <td><%= link_to 'Show', homework_submission %></td>
        <td><%= link_to 'Edit', edit_homework_submission_path(homework_submission) %></td>
        <td><%= link_to 'Destroy', homework_submission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Homework Submission', new_homework_submission_path %>

app/views/homework_submissions/new.html.erb
<div class="container mb-auto py-3 text-center">
  <h2>Submit Assignment</h2>
</div>

<div class="container d-flex justify-content-center">
    <%= render 'form', homework_submission: @homework_submission %>
</div>

<%= link_to 'Back', homework_path(@homework_submission.homework)%>

app/views/homework_submissions/show.html.erb
<div class="container mb-auto py-3 text-center">
  <h2>Homework Submission</h2>
</div>

<div class="container mx-auto">
  <p id="notice"><%= notice %></p>
  <div class="card bg-white mb-3" style="max-width: 100rem;">
    <div class="card-header">
      <h5>Lecture: <%= @homework_submission.homework.get_lecture_name%></h5>
    </div>
    <div class="card-title p-3">
      <div class="row no-gutters">
        <p>
          <strong>Course session user:</strong>
          <%= @homework_submission.course_session_participant_id %>
        </p>
      </div>
      <div class="row no-gutters">
        <p>
          <strong>Pull Request:</strong>
        </p>
      </div>
      <div class="row no-gutters">
        <p>
          <%= @homework_submission.pull_request %>
        </p>
      </div>
      <div class="row no-gutters">
        <p>
          <strong>Is Public: </strong>
          <%= @homework_submission.is_public %>
        </p>
      </div>
    </div>
  </div>
</div>

<%= link_to 'Edit', edit_homework_submission_path(@homework_submission) %> |
<%= link_to 'Course Session', course_session_path(@homework_submission.course_session_participant.course_session_id) %> |
<%= link_to 'Homeworks', homeworks_path %>